### ISSUE TITLE
Rebar.ByCurve Error

### ISSUE THREAD

**Issue by lawrencehooker** [tt-acm/DynamoForRebar#33]
I seem to be getting the same error even just using a selected edge as a curve. Probably user error!

Warning: Rebar.ByCurve operation failed. 
An internal error has occurred.

![rebar error](https://cloud.githubusercontent.com/assets/14805201/10045982/35c05edc-61fe-11e5-87dc-2084be0933e0.jpg)

Any ideas.

Thanks

**Comment by lawrencehooker** [comment]
On further experimentation I have found that the graph works when a single bar is generated. I used an edge just to test this. As soon as I try and create more than one rebar I get the error.
![single rebar](https://cloud.githubusercontent.com/assets/14805201/10049396/3b801766-620f-11e5-8754-5c36427fc991.jpg)
![rebar error 2](https://cloud.githubusercontent.com/assets/14805201/10049398/3cca1748-620f-11e5-9814-b278f847e9df.jpg)

**Comment by moethu** [comment]
Hi Lawrence,
thank you for pointing that out. Maybe there is a little misunderstanding from my side. The Rebar.ByCurve Node creates only one single Bar from a set of connected / joined curves. The curves need to be joined in order to create a single bar.
If you commit numerous unjoined curves to create single bars from you would have to elevate your curves in the list to make the Rebar.ByCurve Node run multiple times.
In your case it might be helopful to use the RebarContainer.ByCurve Node instead. This one uses a list of Curves and creates a single bar from each curve within a container.
I guess the difference doesn't make much sense: Single Bar creates one Bar form multiple curves and Container creates Bars from each Curve.
I will change that in the next release.

**Comment by moethu** [comment]
See #38
