### ISSUE TITLE
Rebar by Curve not possible on Lines

### ISSUE THREAD

**Issue by dietervermeulen** [tt-acm/DynamoForRebar#38]
Hi, it seems that the Rebar and RebarContainer by Curve is only working also on curves. But when you use Dynamo, it happens a lot that the result is a line. Apparently this input is not accepted by the Rebar creation nodes. Any workaround for this?
See script below. In there in want to model rebar from one face to the other using surface divsion nodes. Apply this on a model with two different sized rectangular faces which are parallel to each other. (ie. blended column with variable base and top).

What is remarkable besides that, is that the output of the valid nodes, is not showing when the Rebar package nodes show an error.

![image](https://cloud.githubusercontent.com/assets/12096185/10156898/cd34d41a-6685-11e5-8680-90a91780eaad.png)

**Comment by moethu** [comment]
Hi Dieter,
the nodes are handling Lines. This error is throws by Revits Rebar API because its not able to create a Rebar from this line. This might be due to the coordinates:
![2015-09-29_15h20_54](https://cloud.githubusercontent.com/assets/8201465/10166881/fd02cfc0-66bd-11e5-9101-cf34d0868ee6.png)
Horizontal curves are working fine while line diagonal in Z are not working.

**Comment by moethu** [comment]
@dietervermeulen, found a way using the Rebars normal container:
![2015-09-29_16h11_45](https://cloud.githubusercontent.com/assets/8201465/10168570/4cdba5a6-66c5-11e5-9dd9-a8a2d5c1090f.png)

**Comment by moethu** [comment]
Vector Parameter exposed in 1.4
