### ISSUE TITLE
Regen issue #1

### ISSUE THREAD

**Issue by vasshaug** [tt-acm/DynamoForRebar#41]
Whenever I run a script Dynamo will recreate rebars I already modeled. This is undesirable as it effects performance. If nothing changed - neither should Revit.

(Similar to any other Revit Element Creation Node we need Revit Bake functionality in Dynamo.)

**Comment by moethu** [comment]
Hi @vasshaug ,
in deed, that is a problem. Sadly I cannot manipulate the geometry of an existing Single Rebar Element. Once changed I can leave it as it was or create a new one. I went for creating a new one since this makes more sense than not changing it at all. You won't have this problem with RebarContainers, The API allows changes there.
