### ISSUE TITLE
Regen issue #2

### ISSUE THREAD

**Issue by vasshaug** [tt-acm/DynamoForRebar#43]
If I create rebars somewhere with Dynamo and use the same parameters and nodes to create new rebars elsewhere, Dynamo will delete the previously create rebar before creating the new bars. Completely inefficient workflow on project. This is a Dynamo-Revit issue, but I post it here since it affects rebar workflow very much.

(Similar to any other Revit Element Creation Node we need Revit Bake functionality in Dynamo.)

**Comment by moethu** [comment]
Hi @vasshaug ,
thank you for your feedback. As you already realized, it is a DynamoRevit Issue and I agree very much with you but therefore placing it here doesn't help much since this Repo is using DynamoRevit Nodes and not implementing them. Could you place it in the DynamoRevit GitHub Repo please?
A pre-creation of the Element & Baking option within Dynamo would be great.
